BotManager.WebApplication/Components/CreateViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace BotManager.WebApplication.Components
{
    public class CreateViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            // ReSharper disable once Mvc.ViewComponentViewNotResolved
            return View();
        }
    }
}

BotManager.WebApplication/Components/ModuleViewComponent.cs
using BotManager.WebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace BotManager.WebApplication.Components
{
    public class ModuleViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int botId, List<(string, bool)> data)
        {
            // ReSharper disable once Mvc.ViewComponentViewNotResolved
            return View(new ModuleModel()
            {
                Data = data,
                BotId = botId
            });
        }
    }
}

BotManager.WebApplication/Controllers/HomeController.cs
using System;
using BotManager.Abstractions;
using BotManager.Entities;
using BotManager.WebApplication.Models;
using ExtCore.Data.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace BotManager.WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly IStorage _storage;
        private readonly IBotService _botService;
        private readonly IExtensionsService _extensionsService;

        public HomeController(IStorage storage, IBotService botService, IExtensionsService extensionsService)
        {
            _storage = storage ?? throw new ArgumentNullException(nameof(storage));
            _botService = botService ?? throw new ArgumentNullException(nameof(botService));
            _extensionsService = extensionsService ?? throw new ArgumentNullException(nameof(extensionsService));
        }

        public async Task<IActionResult> Index()
        {
            var model = new IndexModel();

            var bots = await _storage.GetRepository<IBotRepository>().GetAll().ToArrayAsync();
            var updateServices = _extensionsService.GetAllExtensions();

            var  botsExtensions = _storage.GetRepository<IExtensionRepository>().GetAll()
                .ToArray()
                .GroupBy(ex => ex.Bot.Id)
                .ToDictionary(g => g.Key, g =>
                    g.ToDictionary(ex => ex.Name, ex => ex));
            
            foreach (var bot in bots)
            {
                model.BotsWithExtensions.Add(bot, new List<bool>());
                model.Settings.Add(bot.Id, new List<JObject>());
                
                foreach (var service in updateServices)
                {
                    if (botsExtensions.ContainsKey(bot.Id) && botsExtensions[bot.Id].ContainsKey(service.Name))
                    {
                        model.BotsWithExtensions[bot].Add(botsExtensions[bot.Id][service.Name].IsEnabled);
                        model.Settings[bot.Id].Add(botsExtensions[bot.Id][service.Name].Options);
                    }
                    else
                    {
                        model.BotsWithExtensions[bot].Add(false);
                        model.Settings[bot.Id].Add(null);
                    }
                }
            }

            model.ExtensionNames = updateServices
                .Select(ex => ex.Name)
                .ToList();
            
            model.ComponentNames = updateServices
                .Select(ex => ex.ComponentName)
                .ToList();
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(string name, string token)
        {
            if (string.IsNullOrEmpty(name) || name.Length < 3 || name.Length > 100)
                return BadRequest("Name length mus be between 3 and 100");
            
            if (!Token.TryParse(token, out var parsedToken))
                return BadRequest("Can't parse token");
            
            var foundedToken = await _storage.GetRepository<ITokenRepository>()
                .GetAsync(parsedToken.BotExternalId, parsedToken.BotToken);

            if (foundedToken != null)
                parsedToken = foundedToken;

            var botWithToken = await _storage.GetRepository<IBotRepository>()
                .GetAsync(foundedToken);
            
            if(botWithToken != null) return BadRequest("Bot with this token already registered");
            
            var bot = new Bot()
            {
                Name = name,
                Token = parsedToken
            };
            
            bot.IsEnabled = await _botService.TrySetWebHook(bot);
            
            await _storage.GetRepository<IBotRepository>().SaveAsync(bot);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveAsync(int id)
        {
            var bot = await _storage.GetRepository<IBotRepository>().GetAsync(id);
            
            var result =  await _botService.TryRemoveWebHook(bot);

            if (!result) return BadRequest("Can't remove web hook");
            
            await _storage.GetRepository<IBotRepository>().RemoveAsync(id);

            return RedirectToAction("Index");

        }

        [HttpPost]
        public async Task<IActionResult> UpdateDataAsync(int id, int index, bool flag)
        {
            var extensionNames = _extensionsService.GetAllExtensions()
                .Select(ex => ex.Name)
                .ToList();
            
            if (index < 0 || index >= extensionNames.Count)
                return BadRequest("Incorrect index of element");

            var bot = await _storage.GetRepository<IBotRepository>().GetAsync(id);
            
            var extensionName = extensionNames[index];
            
            var extension = await _storage.GetRepository<IExtensionRepository>().GetAsync(id, extensionName);

            if (extension != null && extension.IsEnabled == flag) return RedirectToAction("Index");
            
            extension ??= new Entities.Extension()
            {
                Bot = bot,
                Name = extensionName
            };

            extension.IsEnabled = flag;
            
            await _storage.GetRepository<IExtensionRepository>().SaveOrUpdateAsync(extension);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SetStateAsync(int id, bool flag)
        {
            var bot = await _storage.GetRepository<IBotRepository>().GetAsync(id);
            
            if (bot == null)
                return BadRequest($"Telegram bot with Id: {id} not found");
            
            bot.IsEnabled = flag;
            
            await _storage.GetRepository<IBotRepository>().SaveOrUpdateAsync(bot);
            
            if (flag)
                await _botService.TrySetWebHook(bot);
            
            else
                await _botService.TryRemoveWebHook(bot);
            
            return RedirectToAction("Index");
        }
    }
}

BotManager.WebApplication/Views/Home/Index.cshtml
@model BotManager.WebApplication.Models.IndexModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<body onload="setTab('tabcontent', 'tablinks'), setTab('settingsTab', 'settingsLink')">
<div>
    <div class="tab">
        <ul class="list-group">
            @foreach (var item in Model.BotsWithExtensions)
            {
                var bot = item.Key;
                <li id="@("button" + bot.Id)" class="list-group-item tablinks" onclick="openTab('@("button" + bot.Id)', '@(bot.Id)', 'tabcontent', 'tablinks'), saveTab('@("button" + bot.Id)', '@(bot.Id)', 'tabcontent')">@bot.Name</li>
            }
            <li id="buttonCreate" class="list-group-item tablinks" onclick="openTab('buttonCreate', 'create', 'tabcontent', 'tablinks'), saveTab('buttonCreate', 'create', 'tabcontent')">Добавить...</li>
        </ul>
    </div>
    @foreach (var item in Model.BotsWithExtensions)
    {
        var bot = item.Key;
        <div id="@bot.Id" class="tabcontent">
            <div class="card" style="margin: 8px 8px 0 8px; height: 36%">
                <h5 class="card-header" style="text-align:center">@bot.Name</h5>
                <h5 class="baseMargin">Токен</h5>
                <p class="baseMargin">@bot.Token.ToString()</p>
                <form id="@("switch" + bot.Id)">
                    <div class="baseMargin">
                        <h5 style="display: inline-block; margin: 0 0 0 0; vertical-align: middle">Включен</h5>
                        <label class="switch">
                            <input type="checkbox" name="flag" checked="@bot.IsEnabled" onclick="sendData('/Home/SetState', '@("switch" + bot.Id)')"/>
                            <span class="slider round"></span>
                        </label>
                        <input type="number" name="id" value="@bot.Id" hidden/>
                    </div>
                </form>
                <div class="form-group" style="position:absolute; left: 5px; bottom: 5px; margin-bottom: 0">
                    <form id="@("removeForm" + bot.Id)">
                        <button class="btn btn-primary submitButton" onclick="confirmAction('Вы уверены, что хотите удалить бота?', () => { deleteBot('Home/Remove', '@("removeForm" + bot.Id)', '@bot.Id', '@("button" + bot.Id)')})">Удалить</button>
                        <input type="number" name="id" value="@bot.Id" hidden/>
                    </form>
                </div>
            </div>


            <div class="card module" style="position: absolute">
                <h5 class="card-header" style="text-align: center">Модули</h5>
                <div class="card-body">
                    @await Component.InvokeAsync("Module", new {data = Model.ExtensionNames.Zip(item.Value, (names, values) => (names, values)).ToList(), botId = bot.Id})
                </div>
            </div>

            @for (int i = 0; i < Model.ComponentNames.Count; i++)
            {
                <div class="settingsTab" id="@("module" + i + "bot" + bot.Id)">
                    <div class="card module" style="position: absolute; left:auto; right:8px;">
                        @await Component.InvokeAsync(Model.ComponentNames[i], new {id = bot.Id, settings = Model.Settings[bot.Id][i]})
                    </div>
                </div>
            }
        </div>
    }
    <div>
    </div>
    <div id="create" class="tabcontent" style="text-align: center" onclick="saveTab('buttonCreate','create', 'tabcontent')">
        @await Component.InvokeAsync("Create")
    </div>
</div>
</body>